/**
 * High-fidelity telemetry mock data for RecoverAI command center.
 * Used for offline preview and seamless fallback when backend is starting.
 */

export const INITIAL_METRICS = {
  revenue_at_risk: 648500,
  revenue_recovered: 2840200,
  recovery_rate: 78.6,
  successful_recoveries: 412,
  total_transactions: 524,
  audit_events: 1842,
  average_recovery_time_sec: 4.2,
  autonomous_percentage: 86.4,
  active_ai_agents: 6,
  pipeline_health: 99.8,
};

export const REVENUE_TIMELINE = [
  { time: "00:00", at_risk: 42000, recovered: 98000 },
  { time: "03:00", at_risk: 28000, recovered: 64000 },
  { time: "06:00", at_risk: 65000, recovered: 180000 },
  { time: "09:00", at_risk: 142000, recovered: 420000 },
  { time: "12:00", at_risk: 198000, recovered: 680000 },
  { time: "15:00", at_risk: 245000, recovered: 890000 },
  { time: "18:00", at_risk: 180000, recovered: 720000 },
  { time: "21:00", at_risk: 110000, recovered: 450000 },
];

export const FAILURE_BREAKDOWN = [
  { reason: "Gateway Timeout / Latency Spike", share: 38, count: 198, amount: 246000, color: "#8b5cf6" },
  { reason: "Customer Bank UPI Drop", share: 29, count: 152, amount: 188000, color: "#06b6d4" },
  { reason: "Card 3DS Authentication Expired", share: 19, count: 99, amount: 123000, color: "#f59e0b" },
  { reason: "Insufficient Balance / Limit Cap", share: 14, count: 75, amount: 91500, color: "#f43f5e" },
];

export const INITIAL_CASES = [
  {
    case_id: "CASE-9402",
    transaction_id: "TXN_78491290",
    customer: "Devika Enterprises Ltd",
    email: "finance@devika-enterprises.com",
    customer_tier: "Enterprise Tier 1",
    customer_clv: 1480000,
    amount: 84500,
    currency: "INR",
    failure_reason: "bank_downtime",
    created_at: "2 mins ago",
    status: "human_approval",
    risk_level: "HIGH",
    risk_score: 87,
    diagnosis: {
      diagnosis: "HDFC Core Banking API down during high-value settlement. 3 consecutive mandate retries aborted.",
      agent: "Gemini 1.5 Pro Diagnostic Agent",
      customer_churn_risk: "CRITICAL (92%)",
      recommended_action: "smart_routed_instant_upi",
      confidence: 0.96,
    },
    decision: {
      action: "Switch to Secondary ICICI Node with Instant UPI Intent & 0% Merchant Absorbed Fee",
      rationale: "Enterprise account with ₹14.8L CLV. Immediate switch bypasses HDFC clearing pipe with zero user friction.",
      suggested_discount_pct: 0,
      channel: "Priority Webhook + SMS Direct PayLink",
    },
    guardrail: {
      passed: false,
      requires_human_approval: true,
      reason: "High Value Flag: Transaction amount ₹84,500 exceeds autonomous ceiling (₹50,000). Max auto-attempts reached.",
      triggered_rules: [
        "Rule 4.1: Single settlement > ₹50,000 requires Senior Finance Review",
        "Rule 2.8: Mandate retry frequency exceeded 3 attempts within 10 minutes",
      ],
    },
    pipeline_stage: "guardrail_intercepted",
    logs: [
      { step: "Trigger", time: "09:12:01", status: "passed", detail: "Payment drop detected from webhook" },
      { step: "Diagnosis", time: "09:12:02", status: "passed", detail: "Gemini identified HDFC API failure code 504" },
      { step: "Decision", time: "09:12:03", status: "passed", detail: "Alternative ICICI gateway route generated" },
      { step: "Guardrail", time: "09:12:04", status: "blocked", detail: "Amount ₹84,500 requires human operator sign-off" },
    ],
  },
  {
    case_id: "CASE-9401",
    transaction_id: "TXN_66318920",
    customer: "Arjun Mehta",
    email: "arjun.m@gmail.com",
    customer_tier: "Retail Pro",
    customer_clv: 42000,
    amount: 3499,
    currency: "INR",
    failure_reason: "upi_pin_cancelled",
    created_at: "4 mins ago",
    status: "recovered",
    risk_level: "LOW",
    risk_score: 12,
    diagnosis: {
      diagnosis: "User session expired during PhonePe UPI pin verification dialog.",
      agent: "Gemini 1.5 Flash Diagnostic Agent",
      customer_churn_risk: "LOW (14%)",
      recommended_action: "one_click_whatsapp_checkout",
      confidence: 0.98,
    },
    decision: {
      action: "Send Dynamic 1-Click WhatsApp QuickPay with Pre-filled Cart",
      rationale: "High intent user who drops at pin screen converts 91% when re-engaged via direct messaging.",
      suggested_discount_pct: 5,
      channel: "WhatsApp Interactive Button",
    },
    guardrail: {
      passed: true,
      requires_human_approval: false,
      reason: "Safe auto-execution: Amount under ₹10,000 threshold and low risk profile.",
      triggered_rules: [],
    },
    pipeline_stage: "completed",
    amount_recovered: 3499,
    recovery_latency_sec: 3.8,
    logs: [
      { step: "Trigger", time: "09:08:10", status: "passed", detail: "Transaction failed via UPI" },
      { step: "Diagnosis", time: "09:08:11", status: "passed", detail: "Gemini detected transient UI cancellation" },
      { step: "Decision", time: "09:08:12", status: "passed", detail: "Generated WhatsApp payment intent" },
      { step: "Guardrail", time: "09:08:12", status: "passed", detail: "Autonomous execution approved" },
      { step: "Executor", time: "09:08:13", status: "passed", detail: "WhatsApp API dispatched" },
      { step: "Verifier", time: "09:08:15", status: "passed", detail: "Settlement verified (₹3,499 received)" },
    ],
  },
  {
    case_id: "CASE-9400",
    transaction_id: "TXN_45892104",
    customer: "Zenith Retail Corp",
    email: "payments@zenithretail.in",
    customer_tier: "Enterprise Tier 2",
    customer_clv: 620000,
    amount: 112000,
    currency: "INR",
    failure_reason: "authentication_expired",
    created_at: "6 mins ago",
    status: "human_approval",
    risk_level: "HIGH",
    risk_score: 91,
    diagnosis: {
      diagnosis: "Corporate Credit Card 3DS OTP window timed out. High order volume cart.",
      agent: "Gemini 1.5 Pro Diagnostic Agent",
      customer_churn_risk: "ELEVATED (76%)",
      recommended_action: "account_manager_call_with_virtual_pos",
      confidence: 0.94,
    },
    decision: {
      action: "Initiate Dedicated Payment Link + Priority Account Manager Telegram Alert",
      rationale: "Significant basket size (₹1,12,000). Automated re-attempts could trigger bank fraud freeze.",
      suggested_discount_pct: 0,
      channel: "Virtual POS Link + Account Manager",
    },
    guardrail: {
      passed: false,
      requires_human_approval: true,
      reason: "High Value Flag: ₹1,12,000 exceeds single auto-authorization threshold.",
      triggered_rules: [
        "Rule 4.1: Single settlement > ₹50,000 requires Senior Finance Review",
        "Rule 3.3: Corporate card OTP retry requires fraud verification",
      ],
    },
    pipeline_stage: "guardrail_intercepted",
    logs: [
      { step: "Trigger", time: "09:05:00", status: "passed", detail: "Payment drop detected" },
      { step: "Diagnosis", time: "09:05:01", status: "passed", detail: "Gemini classified OTP timeout" },
      { step: "Decision", time: "09:05:02", status: "passed", detail: "Escalation to VIP virtual link" },
      { step: "Guardrail", time: "09:05:03", status: "blocked", detail: "Blocked: Requires Human Operator Approval" },
    ],
  },
  {
    case_id: "CASE-9399",
    transaction_id: "TXN_12049182",
    customer: "Pooja Sharma",
    email: "pooja.sharma99@yahoo.com",
    customer_tier: "Retail Standard",
    customer_clv: 18500,
    amount: 1899,
    currency: "INR",
    failure_reason: "insufficient_funds",
    created_at: "11 mins ago",
    status: "recovered",
    risk_level: "LOW",
    risk_score: 22,
    diagnosis: {
      diagnosis: "Card account balance deficit. User has verified secondary UPI handle available.",
      agent: "Gemini 1.5 Flash Diagnostic Agent",
      customer_churn_risk: "MEDIUM (45%)",
      recommended_action: "split_payment_or_pay_later_nudge",
      confidence: 0.92,
    },
    decision: {
      action: "Offer 0-Cost BNPL Option or Secondary Google Pay UPI Instant Switch",
      rationale: "Immediate switch to BNPL/UPI recovers 82% of temporary card limit failures.",
      suggested_discount_pct: 0,
      channel: "In-App Smart Toast",
    },
    guardrail: {
      passed: true,
      requires_human_approval: false,
      reason: "Safe auto-execution: Low ticket size, verified user history.",
      triggered_rules: [],
    },
    pipeline_stage: "completed",
    amount_recovered: 1899,
    recovery_latency_sec: 2.9,
    logs: [
      { step: "Trigger", time: "09:00:20", status: "passed", detail: "Card declined insufficient balance" },
      { step: "Diagnosis", time: "09:00:21", status: "passed", detail: "Gemini identified alternative payment option" },
      { step: "Decision", time: "09:00:22", status: "passed", detail: "Smart toast displayed" },
      { step: "Guardrail", time: "09:00:22", status: "passed", detail: "Passed automated guardrail" },
      { step: "Executor", time: "09:00:23", status: "passed", detail: "BNPL switch initiated" },
      { step: "Verifier", time: "09:00:25", status: "passed", detail: "Settlement confirmed ₹1,899" },
    ],
  },
  {
    case_id: "CASE-9398",
    transaction_id: "TXN_99182341",
    customer: "Kunal Singhania",
    email: "kunal@singhania-holdings.co",
    customer_tier: "Enterprise Tier 1",
    customer_clv: 950000,
    amount: 67200,
    currency: "INR",
    failure_reason: "gateway_timeout",
    created_at: "18 mins ago",
    status: "human_approval",
    risk_level: "HIGH",
    risk_score: 79,
    diagnosis: {
      diagnosis: "PayU Gateway latency exceeded 12,000ms threshold during peak clearing.",
      agent: "Gemini 1.5 Pro Diagnostic Agent",
      customer_churn_risk: "HIGH (81%)",
      recommended_action: "reroute_razorpay_direct_mandate",
      confidence: 0.95,
    },
    decision: {
      action: "Execute Instant Failover to Razorpay Direct Clearing Pipe",
      rationale: "Seamless failover prevents double-debit while maintaining enterprise SLA.",
      suggested_discount_pct: 0,
      channel: "Backend Direct Reroute",
    },
    guardrail: {
      passed: false,
      requires_human_approval: true,
      reason: "High Value Flag: ₹67,200 exceeds auto-recovery threshold.",
      triggered_rules: [
        "Rule 4.1: Transactions exceeding ₹50,000 mandate human authorization",
      ],
    },
    pipeline_stage: "guardrail_intercepted",
    logs: [
      { step: "Trigger", time: "08:53:10", status: "passed", detail: "Gateway timeout flagged" },
      { step: "Diagnosis", time: "08:53:11", status: "passed", detail: "Gemini verified PayU latency degradation" },
      { step: "Decision", time: "08:53:12", status: "passed", detail: "Razorpay direct fallback proposed" },
      { step: "Guardrail", time: "08:53:13", status: "blocked", detail: "Blocked for Operator Review" },
    ],
  }
];
